In this project, you'll look at a data science competition helping scientists track animals in a wildlife preserve. The goal is to take images from camera traps and classify which animal, if any, is present. To complete the competition, you'll expand your machine learning skills by creating more powerful neural network models that can take images as inputs and classify them into one of multiple categories.

Some of the things you'll learn are:

How to read image files and prepare them for machine learning
How to use PyTorch to manipulate tensors and build a neural network model
How to build a Convolutional Neural Network that works well with images
How to use that model to make predictions on new images
How to turn those predictions into a submission to the competition

In [1]:
!pip install torch torchvision torchaudio


In [2]:
import os
import sys

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import torch
import torchvision
from PIL import Image
from torchvision import transforms

In [3]:
print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

Platform: win32
Python version: 3.13.2 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 18:49:14) [MSC v.1929 64 bit (AMD64)]
---
matplotlib version: 3.10.0
pandas version: 2.2.3
PIL version: 11.1.0
torch version: 2.7.0+cpu
torchvision version: 0.22.0+cpu


# Working with Tensors in PyTorch

In [4]:
my_values = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_tensor = torch.Tensor(my_values)

print("my_tensor class:", type(my_tensor))
print(my_tensor)

my_tensor class: <class 'torch.Tensor'>
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


# Tensor Attributes

In [5]:
print("my_tensor shape:", my_tensor.shape) 

print("my_tensor dtype:", my_tensor.dtype)  

my_tensor shape: torch.Size([4, 3])
my_tensor dtype: torch.float32


# Print the device of my_tensor.

Tensors also have a .device attribute, which specifies the hardware on which it's stored. By default, tensors are created on the computer's CPU. Let's check if that's the case for my_tensor

In [6]:
print("my_tensor device:", my_tensor.device)

my_tensor device: cpu


Some computers come with GPUs, which allow for bigger and faster model building. In PyTorch, the cuda package is used to access GPUs on Linux and Windows machines; mps is used on Macs. Let's check what's available on our notebook.

In [7]:
# Check if GPUs available via `cuda`
cuda_gpus_available = torch.cuda.is_available()

# Check if GPUs available via `mps`
mps_gpus_available = torch.backends.mps.is_available()

print("cuda GPUs available:", cuda_gpus_available)
print("mps GPUs available:", mps_gpus_available)

cuda GPUs available: False
mps GPUs available: False


# Tensor slicing

Slice my_tensor, assigning its top two rows to left_tensor and its bottom two rows to right_tensor

In [8]:
left_tensor = my_tensor[:2, :]
right_tensor = my_tensor[2:, :]

print("left_tensor class:", type(left_tensor))
print("left_tensor shape:", left_tensor.shape)
print("left_tensor data type:", left_tensor.dtype)
print("left_tensor device:", left_tensor.device)
print(left_tensor)
print()
print("right_tensor class:", type(right_tensor))
print("right_tensor shape:", right_tensor.shape)
print("right_tensor data type:", right_tensor.dtype)
print("right_tensor device:", right_tensor.device)
print(right_tensor)

left_tensor class: <class 'torch.Tensor'>
left_tensor shape: torch.Size([2, 3])
left_tensor data type: torch.float32
left_tensor device: cpu
tensor([[1., 2., 3.],
        [4., 5., 6.]])

right_tensor class: <class 'torch.Tensor'>
right_tensor shape: torch.Size([2, 3])
right_tensor data type: torch.float32
right_tensor device: cpu
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


# Tensor Math

 Use both the mathematical operator and the class method to add left_tensor to right_tensor. Assign the results to summed_tensor_operator and summed_tensor_method, respectively.

In [9]:
summed_tensor_operator = right_tensor + left_tensor
summed_tensor_method = right_tensor.add(left_tensor)

print("summed_tensor_operator class:", type(summed_tensor_operator))
print("summed_tensor_operator shape:", summed_tensor_operator.shape)
print("summed_tensor_operator data type:", summed_tensor_operator.dtype)
print("summed_tensor_operator device:", summed_tensor_operator.device)
print(summed_tensor_operator)
print()
print("summed_tensor_method class:", type(summed_tensor_method))
print("summed_tensor_method shape:", summed_tensor_method.shape)
print("summed_tensor_method data type:", summed_tensor_method.dtype)
print("summed_tensor_method device:", summed_tensor_method.device)
print(summed_tensor_method)

summed_tensor_operator class: <class 'torch.Tensor'>
summed_tensor_operator shape: torch.Size([2, 3])
summed_tensor_operator data type: torch.float32
summed_tensor_operator device: cpu
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])

summed_tensor_method class: <class 'torch.Tensor'>
summed_tensor_method shape: torch.Size([2, 3])
summed_tensor_method data type: torch.float32
summed_tensor_method device: cpu
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])


In [10]:
ew_tensor_operator = left_tensor*right_tensor
ew_tensor_method = right_tensor.mul(left_tensor)

print("ew_tensor_operator class:", type(ew_tensor_operator))
print("ew_tensor_operator shape:", ew_tensor_operator.shape)
print("ew_tensor_operator data type:", ew_tensor_operator.dtype)
print("ew_tensor_operator device:", ew_tensor_operator.device)
print(ew_tensor_operator)
print()
print("ew_tensor_method class:", type(ew_tensor_method))
print("ew_tensor_method shape:", ew_tensor_method.shape)
print("ew_tensor_method data type:", ew_tensor_method.dtype)
print("ew_tensor_method device:", ew_tensor_method.device)
print(ew_tensor_method)

ew_tensor_operator class: <class 'torch.Tensor'>
ew_tensor_operator shape: torch.Size([2, 3])
ew_tensor_operator data type: torch.float32
ew_tensor_operator device: cpu
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])

ew_tensor_method class: <class 'torch.Tensor'>
ew_tensor_method shape: torch.Size([2, 3])
ew_tensor_method data type: torch.float32
ew_tensor_method device: cpu
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


In [11]:
left_tensor * right_tensor == right_tensor * left_tensor

tensor([[True, True, True],
        [True, True, True]])

# matrix multiplication methods

there's matrix multiplication, which combines the rows and columns of two tensors to generate a new one. We can use the @ operator or the .matmul() method.

To see how this works, let's create two new tensors with different shapes.

In [12]:
new_left_tensor = torch.Tensor([[2, 5], [7, 3]])
new_right_tensor = torch.Tensor([[8], [9]])

print("new_left_tensor class:", type(new_left_tensor))
print("new_left_tensor shape:", new_left_tensor.shape)
print("new_left_tensor data type:", new_left_tensor.dtype)
print("new_left_tensor device:", new_left_tensor.device)
print(new_left_tensor)
print()
print("new_right_tensor class:", type(new_right_tensor))
print("new_right_tensor shape:", new_right_tensor.shape)
print("new_right_tensor data type:", new_right_tensor.dtype)
print("new_right_tensor device:", new_right_tensor.device)
print(new_right_tensor)

new_left_tensor class: <class 'torch.Tensor'>
new_left_tensor shape: torch.Size([2, 2])
new_left_tensor data type: torch.float32
new_left_tensor device: cpu
tensor([[2., 5.],
        [7., 3.]])

new_right_tensor class: <class 'torch.Tensor'>
new_right_tensor shape: torch.Size([2, 1])
new_right_tensor data type: torch.float32
new_right_tensor device: cpu
tensor([[8.],
        [9.]])


In [13]:
mm_tensor_operator = new_left_tensor @ new_right_tensor
mm_tensor_method = new_left_tensor.matmul(new_right_tensor)

print("mm_tensor_operator class:", type(mm_tensor_operator))
print("mm_tensor_operator shape:", mm_tensor_operator.shape)
print("mm_tensor_operator data type:", mm_tensor_operator.dtype)
print("mm_tensor_operator device:", mm_tensor_operator.device)
print(mm_tensor_operator)
print()
print("mm_tensor_method class:", type(mm_tensor_method))
print("mm_tensor_method shape:", mm_tensor_method.shape)
print("mm_tensor_method data type:", mm_tensor_method.dtype)
print("mm_tensor_method device:", mm_tensor_method.device)
print(mm_tensor_method)

mm_tensor_operator class: <class 'torch.Tensor'>
mm_tensor_operator shape: torch.Size([2, 1])
mm_tensor_operator data type: torch.float32
mm_tensor_operator device: cpu
tensor([[61.],
        [83.]])

mm_tensor_method class: <class 'torch.Tensor'>
mm_tensor_method shape: torch.Size([2, 1])
mm_tensor_method data type: torch.float32
mm_tensor_method device: cpu
tensor([[61.],
        [83.]])


# Tensor mean calculation

In [14]:
my_tensor_mean = my_tensor.mean()

print("my_tensor_mean class:", type(my_tensor_mean))
print("my_tensor_mean shape:", my_tensor_mean.shape)
print("my_tensor_mean data type:", my_tensor_mean.dtype)
print("my_tensor_mean device:", my_tensor_mean.device)
print("my_tensor mean:", my_tensor_mean)

my_tensor_mean class: <class 'torch.Tensor'>
my_tensor_mean shape: torch.Size([])
my_tensor_mean data type: torch.float32
my_tensor_mean device: cpu
my_tensor mean: tensor(6.5000)


# Calculate the mean for each column in my_tensor.

In [15]:
my_tensor_column_means = my_tensor.mean(dim=[0])

print("my_tensor_column_means class:", type(my_tensor_column_means))
print("my_tensor_column_means shape:", my_tensor_column_means.shape)
print("my_tensor_column_means data type:", my_tensor_column_means.dtype)
print("my_tensor_column_means device:", my_tensor_column_means.device)
print("my_tensor column means:", my_tensor_column_means)

my_tensor_column_means class: <class 'torch.Tensor'>
my_tensor_column_means shape: torch.Size([3])
my_tensor_column_means data type: torch.float32
my_tensor_column_means device: cpu
my_tensor column means: tensor([5.5000, 6.5000, 7.5000])


# Exploring files

data_dir class: <class 'str'>
Data directory: C:/Users/YourUsername/Desktop/data_multiclass\mydata

train_dir class: <class 'str'>
Training data directory: C:/Users/YourUsername/Desktop/data_multiclass\mydata\train_features


FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/YourUsername/Desktop/data_multiclass\\mydata\\train_features'

In [23]:
data_dir = os.path.join("mydata")
train_dir = os.path.join(data_dir, "train_features")

print("data_dir class:", type(data_dir))
print("Data directory:", data_dir)
print()
print("train_dir class:", type(train_dir))
print("Training data directory:", train_dir)

data_dir class: <class 'str'>
Data directory: mydata

train_dir class: <class 'str'>
Training data directory: mydata\train_features


In [24]:
# Check existence
if os.path.exists(train_dir):
    class_directories = os.listdir(train_dir)
    print("class_directories type:", type(class_directories))
    print("class_directories length:", len(class_directories))
    print(class_directories)
else:
    print("🚫 Folder not found:", train_dir)

class_directories type: <class 'list'>
class_directories length: 16489
['.DS_Store', 'ZJ000000.jpg', 'ZJ000001.jpg', 'ZJ000002.jpg', 'ZJ000003.jpg', 'ZJ000004.jpg', 'ZJ000005.jpg', 'ZJ000006.jpg', 'ZJ000007.jpg', 'ZJ000008.jpg', 'ZJ000009.jpg', 'ZJ000010.jpg', 'ZJ000011.jpg', 'ZJ000012.jpg', 'ZJ000013.jpg', 'ZJ000014.jpg', 'ZJ000015.jpg', 'ZJ000016.jpg', 'ZJ000017.jpg', 'ZJ000018.jpg', 'ZJ000019.jpg', 'ZJ000020.jpg', 'ZJ000021.jpg', 'ZJ000022.jpg', 'ZJ000023.jpg', 'ZJ000024.jpg', 'ZJ000025.jpg', 'ZJ000026.jpg', 'ZJ000027.jpg', 'ZJ000028.jpg', 'ZJ000029.jpg', 'ZJ000030.jpg', 'ZJ000031.jpg', 'ZJ000032.jpg', 'ZJ000033.jpg', 'ZJ000034.jpg', 'ZJ000035.jpg', 'ZJ000036.jpg', 'ZJ000037.jpg', 'ZJ000038.jpg', 'ZJ000039.jpg', 'ZJ000040.jpg', 'ZJ000041.jpg', 'ZJ000042.jpg', 'ZJ000043.jpg', 'ZJ000044.jpg', 'ZJ000045.jpg', 'ZJ000046.jpg', 'ZJ000047.jpg', 'ZJ000048.jpg', 'ZJ000049.jpg', 'ZJ000050.jpg', 'ZJ000051.jpg', 'ZJ000052.jpg', 'ZJ000053.jpg', 'ZJ000054.jpg', 'ZJ000055.jpg', 'ZJ000056.jpg', 'ZJ

# mapping data to label

In [25]:
import os
import shutil
import pandas as pd

# Step 1: Define paths
data_dir = os.path.join("mydata")
train_features_dir = os.path.join(data_dir, "train_features")
sorted_dir = os.path.join(data_dir, "train_sorted")
csv_path = os.path.join(data_dir, "train_labels.csv")

# Step 2: Read label CSV
df = pd.read_csv("mydata/train_labels.csv")

# Step 3: Loop over each row in the CSV
for idx, row in df.iterrows():
    image_id = row["id"]
    label = row.drop("id").idxmax()  # Get the column name where the value is 1

    src_img_path = os.path.join(train_features_dir, f"{image_id}.jpg")
    dest_label_dir = os.path.join(sorted_dir, label)
    dest_img_path = os.path.join(dest_label_dir, f"{image_id}.jpg")

    os.makedirs(dest_label_dir, exist_ok=True)  # Create class dir if it doesn't exist

    if os.path.exists(src_img_path):
        shutil.copy(src_img_path, dest_img_path)  # Copy image
    else:
        print(f"❗️Missing file: {src_img_path}")
